config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :users
  get 'pages/about'
  get 'search' => 'search#index'


  root to: 'posts#index'
  resources :posts do
    resources :reviews, only: :create
    resources :likes
  end
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow]

  def index
    @users = policy_scope(User).where.not(id: current_user.id).order(email: :asc)
    @posts = Post.all
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render action: :follow }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user
    if current_user == @user
      @posts = current_user.posts
    else
      @posts = @user.posts
    end
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user = User.find(current_user.id)
    authorize @user
    if
      @user.update(user_params)
      redirect_to current_user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<div class="user-container">
  <div class="user-avatars">
    <%= link_to user_path(user) do  %>
    <% avatar_url =  user.photo || "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1400&q=80" %>
    <%= cl_image_tag avatar_url, height: 60, width: 60, crop: :fill, class: "user-avatar" %>
  </div>
  <div class="users-names">
    <strong><%= user.nickname %></strong>
    <p><%= user.email %></p>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="form-container">
  <%= simple_form_for @user do |f| %>
  <% avatar_url =  current_user.photo || "https://www.w3schools.com/howto/img_avatar.png" %>
  <%= cl_image_tag avatar_url, height: 200, width: 200, crop: :fill, class: "user-avatar" %>

  <%= f.input :photo, input_html: { class: 'hidden' }, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>

  <%= f.input :photo_cache, as: :hidden %>

  <%= f.input :nickname %>

  <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/follow.js.erb
function renderUser(userHTML) {
  const user = document.querySelector(".edit-profile");
  console.log(user);
  user.outerHTML = userHTML;
}

renderUser('<%= j render @user %>');

app/views/users/index.html.erb
<div class="user-wrapper">
  <button onclick="mySearch()"> <i class="fas fa-search"></i> Search Users</button>
  <div id="search" style= 'display: none'>
   <%= render @users %>
 </div>
</div>
<div class="search-wrapper">
  <div class="search-container ">
    <% @posts.each do |post| %>
    <%= render 'shared/search', post: post %>
    <% end %>
  </div>
</div>


<script>
  function mySearch() {
    document.querySelectorAll("#search").forEach((search) => {
      if (search.style.display === "none") {
        search.style.display = "block";
      } else {
        search.style.display = "none";

      }
    });
  }
</script>

app/views/users/show.html.erb
<div class="profile-wrapper">
  <% if  @user == current_user %>
  <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-lock"></i>  <%= @user.email  %>
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
<% else %>
  <!-- <h3><%= @user.email  %></h3> -->
<% end %>
</div>
<div class="profile-container">
  <div class="profile-top">
   <% avatar_url =  @user.photo || "https://images.unsplash.com/photo-1537815749002-de6a533c64db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1090&q=80" %>
   <%= cl_image_tag avatar_url, height: 100, width: 100, crop: :fill, class: "user-avatar" %>
   <h2><%= @user.nickname %></h2>
 </div>
 <div class="profile-followers">
   <h2><%= @posts.count %></h2>
   <p>Publications</p>
 </div>
 <div class="profile-followers">
   <h2><%= @user.followers.count %></h2>
   <p>Followers</p>
 </div>
 <div class="profile-followers">
   <h2><%= @user.following.count %></h2>
   <p>Following</p>
 </div>
</div>
<div class="edit-profile">
  <% if current_user == @user %>
  <%= link_to "Edit profile", edit_user_path, class: "btn-edit-profile" %>

  <% else %>
  <% if current_user.is_following?(@user.id) %>
  <%= link_to "Unfollow", unfollow_user_path(@user.id), method: :post, remote: true, class: "btn-edit-profile" %>
  <% else %>
  <%= link_to "Follow", follow_user_path(@user.id), method: :post, remote: true, class: "btn-edit-profile" %>
  <% end %>
  <% end %>
</div>


<% @posts.each do |post| %>
  <%= render 'shared/cards', post: post %>
<% end %>