config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :users
  get 'pages/about'
  get 'search' => 'search#index'


  root to: 'posts#index'
  resources :posts do
    resources :reviews, only: :create
    resources :likes
  end
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_cards.html.erb
<div class="card-container">
  <div class="card-title">
    <div class="image-top">
      <% avatar_profile =  post.user.photo || "https://www.w3schools.com/howto/img_avatar.png" %>
      <%= cl_image_tag avatar_profile, height: 50, width: 50, crop: :fill, class: "user-profile" %>
      <% title = post.user.nickname || post.user.email%>
      <h3><%= title %></h3>
    </div>
    <div class="dropdown show dropright">
      <a class="btn-instagram dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       <i class="fas fa-ellipsis-h"></i>
     </a>
     <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <a class="dropdown-item" href="#">Action</a>
      <% if policy(post).edit?%>
      <%= link_to 'Edit', post_path(post), class: "dropdown-item" %>
      <% end %>
      <% if policy(post).destroy? %>
      <%= link_to 'Delete',  post, class: "dropdown-item", method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div>
</div>
<div class="card-image">
  <%= cl_image_tag post.photo, height: 400, crop: :fill %>
</div>
<div class="card-comments">
  <%= render partial: 'posts/likes', locals: { post: post } %>
  <%= link_to post_path(post) do  %>
  <i class="far fa-comment"></i>
  <% end %>
</div>
<div class="likes-count">
  <% if post.likes.count > 0 %>
  <%= link_to  post_likes_path(post) do  %>
  <strong><%= post.likes.count %> Likes</strong>
  <% end %>
  <% else %>
  <% end %>
</div>
<div class="card-description">
  <strong><%=title %></strong>
     <% post.title.to_s.split(' ').each do |word| %>
    <% if word.start_with?('#') %>
    <%= link_to word, search_path(query: word) %>
    <%else %>
    <%= word %>
    <%end %>
    <% end %>

</div>
<div class="card-coment">
  <%if post.reviews.size == 0 %>
  <%= link_to post_path(post) do %>
  <h2 >Leave the first comment</h2>
  <% end %>
  <% elsif %>
  <% post.reviews.size == 1  %>
  <h2 onclick="myFunction()">View the <%=post.reviews.size %> coment</h2>
  <% else %>
  <h2 onclick="myFunction()">View the <%=post.reviews.size %> coments</h2>
  <% end %>
  <% post.reviews.each do |review| %>
  <div id="panel" style= 'display: none'>
    <%= render 'reviews/show', review: review %>
  </div>
  <% end %>
</div>
<div class="card-time">
  <%= post.created_at.strftime("%B %d of %Y") %>
</div>
</div>

<script>
  function myFunction() {
    document.querySelectorAll("#panel").forEach((panel) => {
      if (panel.style.display === "none") {
        panel.style.display = "block";
      } else {
        panel.style.display = "none";

      }
    });
  }
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">
  <div class="footer-home">
    <%= link_to root_path do %>
    <i class="fas fa-home"></i>
    <% end %>
  </div>
  <div class="footer-user">
    <%= link_to users_path do %>
    <i class="fas fa-search"></i>
    <% end %>
  </div>
  <div class="footer-user">
    <%= link_to 'messages', conversations_path  %>
  </div>
  <div class="footer-add">
   <% if policy(Post).create? %>
   <%= link_to  new_post_path do %>
   <i class="far fa-plus-square"></i>
   <% end %>
   <% end %>
 </div>
 <div class="footer-like">
   <%= form_with url: search_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
  <%= form.text_field :query, value: params[:query], class: 'form-control mr-sm-2', placeholder: '#search' %>
<% end %>
 </div>
 <div class="footer-image">
  <% if user_signed_in? %>
  <%= link_to  current_user do %>
  <% avatar_url =  current_user.photo || "https://www.w3schools.com/howto/img_avatar.png" %>
  <%= cl_image_tag avatar_url, height: 50, width: 50, crop: :fill, class: "user-avatar" %>
  <% end %>
  <% else %>
  <% end %>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-instagram">
  <div class="navbar-add">
    <% if user_signed_in? %>
    <%= link_to new_post_path  do %>
    <i class="fas fa-camera"></i>
    <% end %>
    <% else %>
    <% end %>
  </div>
  <div class="navbar-logo">
    <h2>INSTAGRAM</h2>
  </div>
  <div class="navbar-log">
    <% if user_signed_in? %>
    <%= link_to pages_about_path do  %>
    <i class="far fa-paper-plane"></i>
    <% end %>
    <% else %>
    <% end %>
  </div>
</div>

app/views/shared/_search.html.erb
<%= link_to post_path(post) do %>
<div class="search-img">
 <%= cl_image_tag post.photo, height: 100, crop: :fill %>
</div>
<% end %>