config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :users
  get 'pages/about'
  get 'search' => 'search#index'


  root to: 'posts#index'
  resources :posts do
    resources :reviews, only: :create
    resources :likes
  end
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  after_commit :create_hash_tags, on: :create
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags
  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :photo, presence: true

  scope :of_followed_users, -> (following_users) { where user_id: following_users }

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  def extract_name_hash_tags
    title.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = policy_scope(Post).of_followed_users(current_user.following).order(created_at: :desc)
  end

  def show
    @review = Review.new
    authorize @review
  end

  def new
    @post = Post.new
    authorize(@post)
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    authorize @post
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def post_params
    params.require(:post).permit(:title, :photo)
  end
end

app/views/posts/_form.html.erb
<div class="form-container">
  <%= simple_form_for @post do |f| %>
    <%= f.input :photo, input_html: { class: 'hidden' }, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>

  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :title %>

  <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/_likes.html.erb
<% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
<div class="likes-heart">
  <i class="fas fa-heart"></i>
</div>
<% else %>
<%= link_to post_likes_path(post), method: :post  do %>
<i class="far fa-heart"></i>
<% end %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="post-wrapper">
  <div class="post-container">
    <% @posts.each do |post| %>
    <%= render 'shared/cards', post: post %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="post-show-container">
  <div class="show-image-top">
    <% avatar_profile =  @post.user.photo || "https://www.w3schools.com/howto/img_avatar.png" %>
    <%= cl_image_tag avatar_profile, crop: :fill%>
    <% title = @post.user.nickname || @post.user.email%>
    <h3><%= title %></h3>
  </div>
  <div class="card-image">
    <%= cl_image_tag @post.photo, height: 400, crop: :fill %>
  </div>
  <div class="card-comments">
    <div id="likes">
      <%= render partial: 'likes', locals: { post: @post } %>
    </div>
    <%= link_to post_path(@post) do  %>
    <i class="far fa-comment"></i>
    <% end %>
    <% if policy(@post).destroy? %>
    <%= link_to @post,  method: :delete, data: { confirm: 'Are you sure?' } do %>
    <i class="fas fa-trash-alt"></i>
    <% end %>
    <% end %>
    <% if policy(@post).edit? %>
    <%= link_to edit_post_path(@post) do %>
    <i class="fas fa-pencil-alt"></i>
    <% end %>
    <% end %>
  </div>
  <div class="likes-count">
    <% if @post.likes.count > 0 %>
    <strong><%= @post.likes.count %> Likes</strong>
    <% else %>
    <% end %>
  </div>
  <div class="card-description">
    <strong><%=title %></strong>
    <% @post.title.to_s.split(' ').each do |word| %>
    <% if word.start_with?('#') %>
    <%= link_to word, search_path(query: word) %>
    <%else %>
    <%= word %>
    <%end %>
    <% end %>
  </div>
  <div class="post-show-coments">
    <h2><span id="review-count"><%=@post.reviews.size%></span> Coments</h2>
  </div>
  <div id="reviews">
    <% @post.reviews.each do |review| %>
    <%= render 'reviews/show', review: review %>
    <% end %>
  </div>
  <%= render 'reviews/form', post: @post, review: @review %>
</div>